version: '3.8'

services:
  # MySQL 服务
  mysql:
    working_dir: /app
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: dev_fs
      MYSQL_USER: dev_fs_user
      MYSQL_PASSWORD: dev_fs_user_pssd_Abc_123
    volumes:
      - ./mysql-data:/var/lib/mysql

  # Redis 服务
  redis:
    working_dir: /app
    image: redis:7.2.4
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    privileged: true

  # NestJS 应用程序服务
  nestjs:
    working_dir: /app
    image: node:lts
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: dev_fs_user
      MYSQL_PASSWORD: dev_fs_user_pssd_Abc_123
      MYSQL_DATABASE: dev_fs
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: mysql://dev_fs_user:dev_fs_user_pssd_Abc_123@mysql:3306/dev_fs
    # 如果你的 NestJS 项目有需要执行数据库迁移的脚本，你可以在这里添加命令
    command: sh -c "npm run start:debug"
